import apiClient from './client';

export const api = {
  getProducts: (params = {}) => apiClient.get('/api/products/', { params }),
  createProduct: (payload) => apiClient.post('/api/products/', payload),
  updateProduct: (id, payload) => apiClient.put(`/api/products/${id}/`, payload),
  patchProduct: (id, payload) => apiClient.patch(`/api/products/${id}/`, payload),
  deleteProduct: (id) => apiClient.delete(`/api/products/${id}/`),
  getCategories: (params = {}) => apiClient.get('/api/categories/', { params }),
  getCategory: (id) => apiClient.get(`/api/categories/${id}/`),
  createCategory: (payload) => apiClient.post('/api/categories/', payload),
  updateCategory: (id, payload) => apiClient.put(`/api/categories/${id}/`, payload),
  patchCategory: (id, payload) => apiClient.patch(`/api/categories/${id}/`, payload),
  deleteCategory: (id) => apiClient.delete(`/api/categories/${id}/`),

  productById: (id) => apiClient.get(`/api/products/${id}/`),
  cart: () => apiClient.get('/api/cart/'),
  addToCart: (payload) => apiClient.post('/api/cart/add/', payload),
  updateCart: (itemId, payload) => apiClient.patch(`/api/cart/items/${itemId}/`, payload),
  removeFromCart: (itemId) => apiClient.delete(`/api/cart/items/${itemId}/remove/`),
  clearCart: () => apiClient.delete('/api/cart/clear/'),
  orders: () => apiClient.get('/api/orders/'),
  orderById: (id) => apiClient.get(`/api/orders/${id}/`),
  checkout: () => apiClient.post('/api/orders/checkout/'),
  digitalLibrary: () => apiClient.get('/api/library/'),
  register: (payload) => apiClient.post('/api/auth/register/', payload),
  login: (payload) => apiClient.post('/api/auth/login/', payload),
  me: () => apiClient.get('/api/auth/me/'),
  adminUsers: () => apiClient.get('/api/auth/users/'),
  adminUserById: (id) => apiClient.get(`/api/auth/users/${id}/`),
  adminUpdateUser: (id, payload) => apiClient.patch(`/api/auth/users/${id}/`, payload),
  adminUpdateUserRole: (id, role) => apiClient.patch(`/api/auth/users/${id}/role/`, { role }),
  adminUpdateUserStatus: (id, is_active) => apiClient.patch(`/api/auth/users/${id}/status/`, { is_active }),
};
