const PRODUCT_TYPE_OPTIONS = [
  { value: 'single', label: 'Carta individual' },
  { value: 'bundle', label: 'Bundle' },
  { value: 'other', label: 'Otro' },
];
const CONDITION_OPTIONS = [{ value: 'NM', label: 'Near Mint' }, { value: 'LP', label: 'Lightly Played' }, { value: 'MP', label: 'Moderately Played' }, { value: 'HP', label: 'Heavily Played' }, { value: 'DMG', label: 'Damaged' }];
const LANGUAGE_OPTIONS = ['EN', 'ES', 'JP', 'PT', 'IT', 'DE', 'FR'];
const initialFormState = { name: '', description: '', product_type: 'single', category_id: '', mtg_card_id: '', condition: 'NM', language: 'EN', is_foil: false, edition: '', image: '', price_clp: '', notes: '', is_active: true };
export { initialFormState, PRODUCT_TYPE_OPTIONS, CONDITION_OPTIONS, LANGUAGE_OPTIONS };

export default function ProductForm({ form, categories, cards, cardQuery, setCardQuery, onCardSearch, onCardSelect, onChange, onSubmit, onCancel, submitLabel }) {
  const isSingle = form.product_type === 'single';
  return <form className="panel-card p-3" onSubmit={onSubmit}><div className="row g-3">
    <div className="col-md-3"><label className="form-label">Tipo de producto</label><select className="form-select" value={form.product_type} onChange={(e) => onChange('product_type', e.target.value)}>{PRODUCT_TYPE_OPTIONS.map((opt) => <option key={opt.value} value={opt.value}>{opt.label}</option>)}</select></div>
    <div className="col-md-5"><label className="form-label">Categoría</label><select className="form-select" value={form.category_id} onChange={(e) => onChange('category_id', e.target.value)} required><option value="">Seleccionar categoría</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div>
    <div className="col-md-4 d-flex align-items-end"><div className="form-check"><input id="active-product" className="form-check-input" type="checkbox" checked={form.is_active} onChange={(e) => onChange('is_active', e.target.checked)} /><label htmlFor="active-product" className="form-check-label">Activo</label></div></div>
    {isSingle ? <><div className="col-12"><h6 className="text-uppercase text-secondary mb-1">Datos MTG</h6></div><div className="col-md-8 d-flex gap-2"><input className="form-control" placeholder="Buscar carta MTG por nombre" value={cardQuery} onChange={(e) => setCardQuery(e.target.value)} /><button type="button" className="btn btn-outline-light" onClick={onCardSearch}>Buscar</button></div><div className="col-md-4"><input className="form-control" placeholder="Edición" value={form.edition} onChange={(e) => onChange('edition', e.target.value)} /></div><div className="col-12"><div className="row g-2">{cards.map((card) => <div className="col-md-6" key={card.id}><button type="button" className="btn btn-dark w-100 text-start d-flex gap-2 align-items-center" onClick={() => onCardSelect(card)}>{card.image_small ? <img src={card.image_small} alt={card.name} width="40" /> : null}<span>{card.name} · {card.set_code?.toUpperCase()} · {card.rarity}</span></button></div>)}</div></div><div className="col-md-3"><label className="form-label">Condición</label><select className="form-select" value={form.condition} onChange={(e) => onChange('condition', e.target.value)}>{CONDITION_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></div><div className="col-md-3"><label className="form-label">Idioma</label><select className="form-select" value={form.language} onChange={(e) => onChange('language', e.target.value)}>{LANGUAGE_OPTIONS.map((l) => <option key={l} value={l}>{l}</option>)}</select></div><div className="col-md-2 d-flex align-items-end"><div className="form-check"><input id="foil" className="form-check-input" type="checkbox" checked={form.is_foil} onChange={(e) => onChange('is_foil', e.target.checked)} /><label htmlFor="foil" className="form-check-label">Foil</label></div></div></> : null}
    <div className="col-12"><h6 className="text-uppercase text-secondary mb-1">Datos del producto</h6></div><div className="col-md-6"><input className="form-control" placeholder="Nombre" value={form.name} onChange={(e) => onChange('name', e.target.value)} required /></div><div className="col-md-6"><input className="form-control" placeholder="URL imagen" value={form.image} onChange={(e) => onChange('image', e.target.value)} /></div><div className="col-12"><textarea className="form-control" rows="2" placeholder="Descripción" value={form.description} onChange={(e) => onChange('description', e.target.value)} /></div><div className="col-12"><textarea className="form-control" rows="2" placeholder="Notas" value={form.notes} onChange={(e) => onChange('notes', e.target.value)} /></div>
    <div className="col-12"><h6 className="text-uppercase text-secondary mb-1">Precio y stock</h6></div><div className="col-md-4"><input className="form-control" type="number" min="0" placeholder="Precio CLP" value={form.price_clp} onChange={(e) => onChange('price_clp', e.target.value)} required /></div><div className="col-md-8"><div className="alert alert-secondary mb-0">El stock se gestiona mediante Kardex, órdenes de compra o movimientos autorizados.</div></div>
    <div className="col-12 d-flex gap-2"><button className="btn btn-primary">{submitLabel}</button>{onCancel ? <button type="button" className="btn btn-outline-secondary" onClick={onCancel}>Cancelar</button> : null}</div>
  </div></form>
}
