# Generated by Django 5.2.13 on 2026-04-29 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MTGCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scryfall_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("set_name", models.CharField(blank=True, max_length=255)),
                ("set_code", models.CharField(blank=True, max_length=20)),
                ("collector_number", models.CharField(blank=True, max_length=20)),
                ("rarity", models.CharField(blank=True, max_length=30)),
                ("mana_cost", models.CharField(blank=True, max_length=80)),
                ("type_line", models.CharField(blank=True, max_length=255)),
                ("oracle_text", models.TextField(blank=True)),
                ("colors", models.JSONField(blank=True, default=list)),
                ("color_identity", models.JSONField(blank=True, default=list)),
                ("legalities", models.JSONField(blank=True, default=dict)),
                ("image_normal", models.URLField(blank=True)),
                ("image_small", models.URLField(blank=True)),
                (
                    "price_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_eur",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("released_at", models.DateField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "set_code", "collector_number"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[
                    ("NM", "Near Mint"),
                    ("LP", "Lightly Played"),
                    ("MP", "Moderately Played"),
                    ("HP", "Heavily Played"),
                    ("DMG", "Damaged"),
                ],
                default="NM",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="edition",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="is_foil",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="language",
            field=models.CharField(default="EN", max_length=40),
        ),
        migrations.AddField(
            model_name="product",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="price_clp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("single", "Carta individual"),
                    ("sealed", "Producto sellado"),
                    ("accessory", "Accesorio"),
                    ("deck", "Mazo"),
                    ("bundle", "Bundle"),
                ],
                default="single",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="mtg_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.mtgcard",
            ),
        ),
    ]
