# Generated by Django 5.2.13 on 2026-04-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_mtgcard_product_condition_product_edition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRateConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="default", max_length=80)),
                ("usd_to_clp", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceFeeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="default", max_length=80)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "flat_fee_clp",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShippingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="default", max_length=80)),
                (
                    "base_clp",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "per_item_clp",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("website_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="mtgcard",
            options={},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.RemoveField(
            model_name="mtgcard",
            name="price_eur",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
