# Generated by Django 5.2.13 on 2026-04-30 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_normalize_product_type_values"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mtgcard",
            options={"ordering": ["name", "set_code", "collector_number"]},
        ),
        migrations.RemoveField(
            model_name="mtgcard",
            name="legalities",
        ),
        migrations.RemoveField(
            model_name="mtgcard",
            name="price_usd",
        ),
        migrations.AddField(
            model_name="mtgcard",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="mtgcard",
            name="image_large",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="mtgcard",
            name="printed_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="mtgcard",
            name="scryfall_uri",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
