# Generated by Django 5.2.13 on 2026-04-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_mtgcard_options_remove_mtgcard_legalities_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="default", max_length=80)),
                (
                    "usd_to_clp",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=12),
                ),
                (
                    "import_factor",
                    models.DecimalField(decimal_places=2, default=1.3, max_digits=5),
                ),
                (
                    "risk_factor",
                    models.DecimalField(decimal_places=2, default=1.1, max_digits=5),
                ),
                (
                    "margin_factor",
                    models.DecimalField(decimal_places=2, default=1.25, max_digits=5),
                ),
                ("round_to", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración de precios",
                "verbose_name_plural": "Configuraciones de precios",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="price_clp_final",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="price_clp_suggested",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="price_usd_reference",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="product",
            name="pricing_last_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="pricing_source",
            field=models.CharField(
                choices=[("SCRYFALL", "Scryfall"), ("MANUAL", "Manual")],
                default="MANUAL",
                max_length=20,
            ),
        ),
    ]
